### ISSUE TITLE
Cannot install Trust/KaKu E27 Dimmable (ZLED-2209)

### ISSUE THREAD

**Issue by tfreriks** [athombv/nl.klikaanklikuit.zigbee#1]
Cannot get passed:

---
Er ging iets fout bij het toevoegen van dit apparaat, probeer het later opnieuw.
Lukt het niet om het apparaat aan Homey toe te voegen, probeer het dan eerst opnieuw in te stellen.
---

I tried 1x On/Off and also 5x On/Off (paring mode) for about 10 times

Also tried to Clear ZigBee Network in my Homey, problem persists...

**Comment by RobinBol** [comment]
Hi, are you sure the reset is performed correctly? If not this is very likely the cause of the error message. The bulb should blink twice after the reset to indicate it has been reset successfully, if it does not the reset was not performed correctly.

**Comment by RobinBol** [comment]
Hi, are you sure the reset is performed correctly? If not this is very likely the cause of the error message. The bulb should blink twice after the reset to indicate it has been reset successfully, if it does not the reset was not performed correctly.

**Comment by tfreriks** [comment]
Robin,

Yes I did. (5x On/Off = blink twice)
Adding new Light Bulbs is a bit buggy, but after trying for 2-10 times (Reset included) I got every Bulb added in the end.

Now all the Bulbs are added the App works fine 95% of the time.

Sometimes (5%) Homey says (something like): "Kan niet schakelen" (not the exact words)

resuming, my current bugs:

- Adding new Bulbs buggy
- Sometimes "Kan niet schakelen"

**Comment by RobinBol** [comment]
Ok, thanks for reporting your issues. Could you mention which firmware version you are on exactly?

**Comment by tfreriks** [comment]
At the time of my problems I was at V1.01 I think
Now, at V1.03 (Beta) I found no problems anymore (except Home responding to the task "Turn of all Lights" as: "Kan niet schakelen" which is a Homey problem I think, not Kaku)

So: Great job!

**Comment by RobinBol** [comment]
Thanks for reporting your issues, it seems most of them are solved in the meanwhile, if you encouter issues with speech please create an issue in the homey issue tracker: https://github.com/athombv/homey/issues
