### ISSUE TITLE
Support for KAKU / Trust ZigBee sensors

### ISSUE THREAD

**Issue by Veldkornet** [athombv/nl.klikaanklikuit.zigbee#4]
Currently only the LED lamps are supported. Could you please add support for the sensors as well from their [zigbee line](https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn.html?p=1)?

[ZWLD-100 Draadloze Waterlekdetector](https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zwld-100-draadloze-waterlekdetector.html)
[ZCTS-808 Draadloze Contactsensor](https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zcts-808-zigbee-draadloze-contactsensor.html)
[ZPIR-8000 Draadloze Bewegingssensor](https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zpir-8000-draadloze-bewegingssensor.html)
[ZYCT-202 Afstandsbediening met Muurbevestiging](https://www.klikaanklikuit.nl/nl/producten/zigbee-lijn/zyct-202-afstandsbediening-met-muurbevestiging.html)
[ZSDR-850 Draadloze Rookmelder](https://www.klikaanklikuit.nl/nl/zigbee-smoke-detector.html)

Additionally, it appears as though their are 8 LED lights, but only 7 are supported by the app. So looks as though 1 is missing. Although since the app doesn’t show the model numbers, I can’t check.

**Comment by Zignature** [comment]
I would very much appreciate support for the ZYCT-202 switch too :)

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
